# Generated by Django 5.2.14 on 2026-05-24 13:14

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ImportBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_type', models.CharField(choices=[('sap-fuel', 'SAP fuel/procurement'), ('utility-electricity', 'Utility electricity'), ('travel-corporate', 'Corporate travel')], max_length=32)),
                ('filename', models.CharField(max_length=255)),
                ('received_at', models.DateTimeField(auto_now_add=True)),
                ('row_count', models.PositiveIntegerField(default=0)),
                ('imported_count', models.PositiveIntegerField(default=0)),
                ('failed_count', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('processing', 'Processing'), ('complete', 'Complete'), ('failed', 'Failed')], default='processing', max_length=24)),
            ],
        ),
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('source_type', models.CharField(choices=[('sap-fuel', 'SAP fuel/procurement'), ('utility-electricity', 'Utility electricity'), ('travel-corporate', 'Corporate travel')], max_length=32)),
                ('config', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('slug', models.SlugField(unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='NormalizedRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raw_payload', models.JSONField(default=dict)),
                ('record_type', models.CharField(max_length=32)),
                ('category', models.CharField(max_length=128)),
                ('emission_scope', models.CharField(choices=[('scope1', 'Scope 1'), ('scope2', 'Scope 2'), ('scope3', 'Scope 3')], max_length=16)),
                ('activity_start', models.DateField(blank=True, null=True)),
                ('activity_end', models.DateField(blank=True, null=True)),
                ('vendor', models.CharField(blank=True, max_length=128)),
                ('location', models.CharField(blank=True, max_length=128)),
                ('quantity', models.FloatField(blank=True, null=True)),
                ('quantity_unit', models.CharField(blank=True, max_length=32)),
                ('normalized_quantity', models.FloatField(default=0.0)),
                ('normalized_unit', models.CharField(blank=True, max_length=32)),
                ('emissions_kg_co2e', models.FloatField(default=0.0)),
                ('suspicious_reason', models.CharField(blank=True, max_length=256)),
                ('status', models.CharField(choices=[('pending_review', 'Pending review'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending_review', max_length=24)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_records', to=settings.AUTH_USER_MODEL)),
                ('import_batch', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='records', to='core.importbatch')),
                ('last_editor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='edited_records', to=settings.AUTH_USER_MODEL)),
                ('source', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='records', to='core.source')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='core.tenant')),
            ],
        ),
        migrations.CreateModel(
            name='AuditEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(max_length=64)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('data', models.JSONField(blank=True, default=dict)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_entries', to='core.normalizedrecord')),
            ],
        ),
        migrations.AddField(
            model_name='importbatch',
            name='source',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='imports', to='core.source'),
        ),
        migrations.AddField(
            model_name='source',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sources', to='core.tenant'),
        ),
        migrations.AddField(
            model_name='importbatch',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imports', to='core.tenant'),
        ),
    ]
