# Generated by Django 5.2.14 on 2026-05-26 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='normalizedrecord',
            name='rejection_reason',
            field=models.TextField(blank=True, null=True),
        ),
    ]
